### PR TITLE
ci: enforce conventional commits

### PR DESCRIPTION
**Pull request by kevgo**
I've struggled with conventional commits on enough PRs to automate this. The app we currently seem to use (https://github.com/zeke/semantic-pull-requests) is [no longer maintained](https://github.com/zeke/semantic-pull-requests#%EF%B8%8F-this-service-is-no-longer-maintained-%EF%B8%8F). This sets up the recommended GitHub Action instead.

- [x] checks the commit message
- [x] allows the custom types used by Ory
- [x] works with external forks
- [x] enforces lowercase 

I'm doing a few test commits to verify that this works, then will tag people.
Edit: this is done now.

### CODE REVIEW

**Comment by kevgo** [comment]
@aeneasr what do you think? I'm happy to add this to all the other repos as well.

**Comment by aeneasr** [comment]
Nice! We can sync this across al repos by using github.com/ory/meta which has a sync action: https://github.com/ory/meta/blob/master/.github/workflows/sync.yml

**Comment by kevgo** [comment]
Cool that you have a solution to sync such things across so many repos! 

How do we delete the now obsolete [.github/semantic.yml](https://github.com/ory/prettier-styles/blob/master/.github/semantic.yml) from all repos? After a cursory glance, I see the sync script only copying files from the meta repo to the target repos (except for the ISSUE_TEMPLATE directory, which it clears out first).

**Comment by aeneasr** [comment]
> How do we delete the now obsolete [.github/semantic.yml](https://github.com/ory/prettier-styles/blob/master/.github/semantic.yml) from all repos? After a cursory glance, I see the sync script only copying files from the meta repo to the target repos (except for the ISSUE_TEMPLATE directory, which it clears out first).

Good question, it might make sense to use rclone / rcopy instead of a dumb `cp`?

**Comment by kevgo** [comment]
I don't have a good answer right now. Isn't rcopy/rclone similar to deleting the target dir and copying everything over again (just faster)? If we do anything destructive (deleting files), I'm exponentially more concerned about committing straight to master while bypassing all CI and reviews.

I have created https://github.com/ory/meta/issues/150 to keep thinking about this specific issue. Merging this PR for conventional commit enforcement in this repo in for now.

**Pull request merged**
